default: &default
  adapter: postgresql
  encoding: unicode
  username: b4k3r
  password: m4sherman
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_development
test:
  <<: *default
  database: blog_test

production:
  url: <%= ENV['DATABASE_URL'] %>

